# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: 2
info:
  title: DataValidation Batch API
  description: Interacting with the DataValidation site via an API
  version: "1.0"
# the domain of the service
host: api.datavalidation.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /list:
    get:
      summary: A list of lists that are in the system
      description: A list consists of email addresses that have been uploaded into the system
      tags:
        - Products
      responses:
        200:
          description: An list of lists
          schema:
            type: array
            items:
              $ref: Lists
        default:
          description: Unexpected error
          schema:
            $ref: Error
  /list:
    post:
      summary: Add a CSV of email addresses to the list
      description: For an initial upload of a CSV, this can be used. It will create a list and add the CSV data to it, optionally keeping the metadata (the non-email containing columns) in the CSV.
      parameters:
        - name: header
          in: query
          description: Is there a header row present in the CSV data (0 = no, 1 = yes)
          required: true
          type: number
          format: int
        - name: email_col
          in: query
          description: Which column is the email address in? (0 = first column)
          required: true
          type: number
          format: int
        - name: metadata
          required: true
          in: query
          type: string
          format: other
          description: Should the metadata (non-email) in the CSV be stored? (true or false)
        - name: slug_col
          required: false
          in: query
          type: string
          description: The slug that should be used to identify this list. If it is not supplied, one will be generated

      responses:
        200:
          description: An list of lists
          schema:
            type: array
            items:
              $ref: List
        default:
          description: Unexpected error
          schema:
            $ref: Error
  /list/{slug}:
    get:
      summary: Retrieve and individual list
      description: An individual list. This contains...
      responses:
        200:
          description: The details for the given {list_slug}
          schema:
            type: object
            items:
              $ref: List
        default:
          description: Unexpected error
          schema:
            $ref: Error
  /list/{slug}:
    delete:
      summary: Remove an individual list
      description: Removes a list from the system
      responses:
        204:
          description: Nothing returned on succuess
          schema:
            type: object
            items:
              $ref: List
        default:
          description: Unexpected error
          schema:
            $ref: Error
  /list/{list_slug}/subscribe.csv:
    post:
      summary: Add a CSV to the system
      description: Adding a list of users in CSV format to the system
      parameters:
        - name: header
          in: query
          description: Is there a header row present in the CSV data (0 = no, 1 = yes)
          required: true
          type: number
          format: int
        - name: email_col
          in: query
          description: Which column is the email address in? (0 = first column)
          required: true
          type: number
          format: int
        - name: metadata
          required: true
          in: query
          type: string
          format: other
          description: Should the metadata (non-email) in the CSV be stored? (true or false)
        - name: slug_col
          required: false
          in: query
          type: string
          description: The slug that should be used to identify this list. If it is not supplied, one will be generated
      tags:
        - Estimates
      responses:
        200:
          description: An array of products
          schema:
            type: List
            items:
              $ref: List
        default:
          description: Unexpected error
          schema:
            $ref: Error
  /list/{list_slug}/export.csv:
    get:
      summary: Retrieves the list in CSV format
      description: Similar to the /list/{list_slug}/ this will retrieve the information we have for a given {list_slug}. The difference is that the format will be in CSV, optionally including any metadata that was originally loaded into the system (using /list/subscribe.csv)
      responses:
        200:
          description: A location of the CSV
          schema:
            $ref: List
        default:
          description: Unexpected error
          schema:
            $ref: Error
definitions:
  Lists:
    properties:
      members:
        type: array
        description: An array of $List objects
  List:
    properties:
      members:
        type: string
        description: An email address of an individual (e.g. a line from a CSV)
  Error:
    properties:
      status:
        type: int
      errors:
        type: string
