apiVersion: 1.0
swaggerVersion: 1.2
apis:
  - path: /batch.json
    description: Public batch API
  - path: /realtime.json
    description: Public real-time API
info:
  title: Synapp.io APIs
  description: Synapp.io APIs
  contact: sales@synapp.io
  license: MIT maybe?
